version: '3.7'

services:
  api:
    restart: always
    build:
      context: .
      target: development
    ports:
      - 5000:5000
    depends_on:
      - db
    volumes:
      - ./neoway:/app/neoway/
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "neoway"
      POSTGRES_USER: "neoway"
      POSTGRES_DB: "neoway"